lecture3/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="hello"),
    path("<str:name>", views.greet, name="hello")
]

lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls"))
]

lecture3/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="newyear"),
    
]

lecture3/todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add")
    
]

lecture3/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello.html")

def greet(request, name):
    return render(request, "greet.html", {
        "name" : name.capitalize(),
    })

lecture3/newyear/views.py
from django.shortcuts import render
import datetime as dt
from django.http import HttpResponse

# Create your views here.
def index(request):
    now = dt.datetime.now()

    return render(request, "index.html", {
        "newyear": now.month == 1 and now.day == 1,
    })

lecture3/todo/views.py
from django.shortcuts import render
import datetime as dt
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse


class newtaskform(forms.Form):
    task = forms.CharField(label="new task")

    


# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = ["make coffee", "tea", "spill", "hello"]
    return render(request, "indextodo.html", {
        "tasks" : request.session["tasks"]
    })


def add(request):
    if request.method == "POST":
        form = newtaskform(request.POST)
        if form.is_valid():  # <-- Add parentheses here
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("todo:index"))
        else:
            return render(request, "add.html", {
                "form": form
            })

    return render(request, "add.html", {
        "form": newtaskform()
    })

lecture3/hello/templates/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hello {{ name }} </h1>
</body>
</html>

lecture3/hello/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <h1>hello html </h1>
</body>
</html>

lecture3/newyear/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>is it new year</title>
</head>
<body>
    <div style="margin-left: auto; margin-right: auto; align-items: center; align-content: center; text-align: center;">
    <h1> Is it new year? </h1>
    <br>

    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1> NO </h1>
    {% endif %}

    </div>
</body>
</html>

lecture3/todo/templates/add.html
{% extends "layout.html" %}

{% block body %}

    <h1>Add Task</h1>

    <form action="{% url 'todo:add' %}" method="post">
        {{ form }}
        <input type="submit" value="Add task">
        {% csrf_token %}
    </form>

    <a href="{% url 'todo:index' %}" style=" color: aliceblue; font-size: small; text-decoration: none;"> View all tasks</a> 

{% endblock %}

lecture3/todo/templates/indextodo.html
{% extends "layout.html" %}


{% block body%}
        <h1 >TODO LIST</h1>
    
        <ol>
            {% for task in tasks %}
                <li> {{ task }} </li>

                {% empty %}
                    <li>no task</li>
            {% endfor %}

             <a href="{% url 'todo:add'%}" style=" color: aliceblue; font-size: small; text-decoration: none;"> Add a task</a> 
        </ol>
{% endblock %}

   

lecture3/todo/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>todo list</title>
</head>
<body style="background-color: rgb(37, 37, 37);">
    <div style="margin-left: auto; margin-right: auto; align-items: center; font-family: 'Courier New', Courier, monospace; color: bisque; margin: 20px;">

        {% block body %}
        {% endblock %}

    </div>
</body>
</html>